### ISSUE TITLE
Support Elixir 1.5

### ISSUE THREAD

**Issue by jayjun** [nanobox-io/nanobox-engine-elixir#21]
It’s been mentioned on Slack (#elixir) couple of times, figured I should create an issue to track this.

**Comment by jayjun** [comment]
```yaml
run.config:
  engine.config:
    runtime: elixir-1.5
```
surprisingly worked. The README should be updated to show Elixir 1.5 support.

In addition, consider bumping the default version to 1.5.
