### ISSUE TITLE
Add support for Elixir 1.6.6 and Erlang 21.0

### ISSUE THREAD

**Issue by silviurosu** [nanobox-io/nanobox-engine-elixir#33]
There are some features that I want to use from this release.

**Comment by ndac-todoroki** [comment]
Probably a duplicate of #29 (where documentation is not enough nor updated...),

```yaml
run.config:
  # elixir runtime
  engine: elixir
  engine.config:
    runtime: elixir-1.6.6
    erlang_runtime: erlang-21
```

This worked for me.

```
/app $ elixir -v
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Elixir 1.6.6 (compiled with OTP 21)
```
